### ISSUE TITLE
(editorial): Thingness (CH-22), sdfThing vs. Thing (CH-23); also CH-7, CH-8, CH-9, CH-11

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#112]
Also, clearly separate Thing (generic IoT term) from sdfThing

**Comment by cabo** [comment]
SDF can be used outside IoT.

**Comment by mjkoster** [comment]
Define sdfThing in the terminology section and keep it narrow, rewrite the abstract and remove IoT
