### ISSUE TITLE
URIs as unit values

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#12]
Should we explicitly add that non-colon values for the "unit" quality are registered SenML units and colon-containing values are general URIs?
(OneDM can still decide which of these it wants to use and when, but the language would be more flexible.)

\[Via discussion at OneDM call 2021-01-11]

**Comment by akeranen** [comment]
This seems like a good way to cover units that are not suitable for the SenML IANA registry. Such units would not provide the same level of interoperability so primary option, when possible (i.e., the units are reasonable engineering units), should be to add new units to the IANA registry and provide the scale/offset mapping when needed. 

Perhaps we should revisit this issue when we get first use cases of models with units not suitable for the IANA registry.

**Comment by cabo** [comment]
We now seem to have a potential use case: the unit "slug" is defined in Microsoft DTDL, but is not currently scheduled to be added to the SenML second registry.

Ways out:

* set up the SenML second registry to be the kitchen sink, by needing a registration even for less likely units,
* open up to URIs.

The latter has a certain danger in that it is easier to create an ecosystem-specific URI than to register a (likely common) SenML unit, so it promotes fragmentation.  There is also the discovery problem: How does one find the *right* URI even for a well-defined ecosystem?

**Comment by akeranen** [comment]
Discussed today in OneDM call: perhaps 3-level approach makes sense: 1) SenML units as default option 2) set of registered CURIE prefixes to most common unit ontologies (ucum, qudt, om, etc.) 3) full URIs if 1 or 2 don't work (with appropriate warnings for challenges with interop when using 2 or 3).

Also having ontology mapping from SenML units to other common units ontologies to help with translations.

**Comment by cabo** [comment]
I don’t think we want to register prefixes. Well, at least they should still be declared in the document. Can’t mix Curie and Uris, always needs to be Curie then.

**Comment by cabo** [comment]
closed by e0b6423
