### ISSUE TITLE
Type and subtype coexistence

### ISSUE THREAD

**Issue by akeranen** [ietf-wg-asdf/SDF#13]
Currently we can have type or subtype data qualities. We should clarify can we have both at the same time. How about e.g., "string" type and "unix-time" subtype?

**Comment by WAvdBeek** [comment]
I always understood that one should have a type and optionally an subtype.

**Comment by cabo** [comment]
Indeed, that was what I got from the word `subtype` as well.  
Should we say which `type` values can be used for each `subtype`?
I believe currently the `subtype` implies a specific `type` (disregarding Ari's example), so the `type` is noise.

**Comment by WAvdBeek** [comment]
for code generation it is definitely not noise, the subtype is just another constrained on the type.

**Comment by nwidell** [comment]
I'm not sure that a subtype is always tied to a particular type, e.g. unix-time as signed integer can be represented in multiple ways if you want to include fractions. 
Anyway, perhaps it is better to say "format" as a way to indicate that the value is specified in a particular format. 
BTW, should we specify a time format (unix-time, ISO8601 or RFC 3339)?
