### ISSUE TITLE
Mandatory/optional SDF information block

### ISSUE THREAD

**Issue by akeranen** [ietf-wg-asdf/SDF#23]
Currently the [information block](https://ietf-wg-asdf.github.io/SDF/sdf.html#name-information-block) is mandatory for all SDF definitions. While being highly useful for final (e.g., contributed to OneDM) definitions, it is often unnecessary boilerplate during development time. The base SDF specification could have the info block, and probably all qualities in the block, as optional and it would be mandatory only when actually needed.

**Comment by WAvdBeek** [comment]
why would we care about that part of the syntax if the work is still in development?

**Comment by akeranen** [comment]
Because it's useful to be able to use validation also during development time.
