### ISSUE TITLE
Contribute to more than the default namespace?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#28]
SDF 1.1 models contribute their definitions to the default namespace.
Should there be a way to contribute to other namespaces as well?
How can this be done without violating the RFC 6901 JSON pointer fragment identifier syntax?

**Comment by cabo** [comment]
It may also be a bit opaque (editorial problem) that the default namespace is the one being contributed to.

**Comment by cabo** [comment]
Another view may be "have multiple models in a single blob/file/document/JSON text..."

**Comment by mjkoster** [comment]
"We always" intended to be able to override the defaultNamespace by using an explicit prefix for the entity being defined. It seem simple and straightforward.

**Comment by cabo** [comment]
I'm still a bit unclear about the use case for importing into multiple namespaces.
We could, of course, define all names to be curies if they contain a colon..
We would need to define how that interacts with JSON Pointer.

**Comment by mjkoster** [comment]
It's hard to imagine a use case for two destination namespaces at the same time. 

One use case is if you want to create or modify some definition in a namespace you're importing from.

**Comment by akeranen** [comment]
One use case I'm thinking of is that you compose a Thing that has definitions (Things and Objects) from various namespaces (e.g., OCF Fridge with IPSO Temperature sensor) and you want to have the full set described in a single file (you could perhaps use different files and sdfRef things from different namespaces to get roughly same effect).

**Comment by cabo** [comment]
Maybe don't do this now, but add extensibility considerations here.
We could add something like an export declaration later, and might want to group that with namespace/defaultnamespace.

**Comment by cabo** [comment]
(This is about named<...>, i.e. the names this model defines, but there also are quality names which also might want to use namespaces.)
