### ISSUE TITLE
Define "version" field in info block

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#29]
Going towards the RFC, the "version" field in the info block needs to have a more detailed definition.
Some of the details will come from OneDM, but SDF itself may have a framework into which the OneDM processes fit.

**Comment by cabo** [comment]
See also <https://mailarchive.ietf.org/arch/msg/asdf/bfoGyTrA_hzUI6nHshe-OxpbFHI>

**Comment by akeranen** [comment]
Perhaps following the [WoT TD approach](https://www.w3.org/TR/2020/REC-wot-thing-description-20200409/#thing) with additional `created` and `modified` qualities makes sense.
