### ISSUE TITLE
Split up `jsonschema` CDDL definition (co-occurrence)

### ISSUE THREAD

**Issue by JKRhb** [ietf-wg-asdf/SDF#34]
At the moment, there is only one `jsonschema` definition included in the CDDL schema that is used for all possible data types. If I am not mistaken, this allows Data Qualities to be, for example, of type `string` while also having a `minimum` or a number of `maxItems`.

As this is probably not intended, I wanted to propose to split up this part of the schema into type specific definitions.

**Comment by cabo** [comment]
The reason this hasn't been done yet is that the CDDL-to-jso converter would need to be able to handle the choice.
This is still a TODO...

**Comment by cabo** [comment]
I looked at doing this now.

Playground's sdfObject/sdfobject-ipso-temperature.sdf.json is an interesting case as the minimum/maximum constraints are in the individual choices such as "RESERVED" and "VENDOR SPECIFIC", and the type=integer is at the same level as the choice "Measurement_Quality_Indicator".

I don't think this can be supported directly without blowing up the grammar even more, so it would mean that the type: "integer" needs to be repeated in the choices what want to use number/integer constraints.

**Comment by mjkoster** [comment]
It seems reasonable to require explicit range and type constraints at leaf levels of the sdfChoice construct when it's being used for range splitting. The top level range constraint in the playground example (min 0 max 23) does seem redundant. As a general observation, sdfChoice seems to do most of its "work" in the leaf nodes, and any constraints stated at the top level need to be hoisted (or lowered) to the leaf nodes for validation.

**Comment by cabo** [comment]
2023-05-25 interim: a grammar-based tool like CDDL can't reasonably express the semantic constraint that there e.g. has to be a type in the data qualities or in each branch of the sdfChoice.  So cannot "solve" this issue right now.
