### ISSUE TITLE
Feature: Composite sdfData types and sdfProperty types

### ISSUE THREAD

**Issue by mjkoster** [ietf-wg-asdf/SDF#4]
SDF should allow defining an sdfProperty that is composed of multiple sdfProperty or sdfData types. Likewise, an sdfData definition should be composable from sdfData types.

The feature is needed to modelsystems that allow  read/write and pub/sub interaction with multiple data elements. 

Currently, we allow sdfAction and sdfEvent input and output data to be composed of multiple sdfData types. We could extend sdfProperty to allow multiple sdfData elements using the same (sdfData, sdfInputData, sdfOutputData) declarations that are provided for sdfAction and sdfEvent.

```
"sdfProperty": {
  "simple1" : {
    "type": "string"
  },
  "compound1": {
    "sdfData": {
      "element1": { "type": "number" },
      "element2": { "type": "string" }
    }
  }
}
```

**Comment by cabo** [comment]
The action/event version of the composition is a bit broken as we cannot name the fields/members created by including data types.  So if we have RGB input data, we can say `["intensity", "intensity", "intensity"]`, but we cannot say which is R, G, or B.  (Note that "saying" that is also creating a naming problem similar to the enum problem.)

So far, sdfData did not "declare" (create) actual fields/members, but only defined types.  I read this proposal as saying once the sdfData items are nested in an sdfProperty, they do create those fields/members.

**Comment by mjkoster** [comment]
@cabo The way I understand sdfData wrt your comment is that the named  elements in the sdfData construct create a template for an interaction to pass data, and the sdfInputData list indicates directionality. If some "instance" of sdfData outside the local scope of the interaction is pointed to in sdfInputData list, I think it should still be understood as a template for passing data. 

The use of "sdfData" with sdfProperty could be understood as creating state elements, so we may want to consider a design pattern that explicitly creates the state elements as simple properties, and additionally creates the composite property using pointer references to the simple properties. We can work through an example using RGB if there are questions on the detailed schema constraints.

I think this suggests that more discussion may be needed around the idea of a complementary "sdfOutputData" list.

**Comment by akeranen** [comment]
I think a useful (/must?) property for compound types is that you can flatten (and reconstruct for round-tripping) them easily for ecosystems that don't have compound types but can refer to other objects from properties for the same effect. The design proposed by @mjkoster seems to enable that but would be worthwhile experimenting with.

**Comment by mjkoster** [comment]
@akeranen I agree and I think the proposed design allows for named fields in a compound property that are references to pre-defined properties. I expect to leave it to the mapping file/protocol binding to decide how to pack/unpack for transfer or storage. The names are convenient tags and the references allow for nesting in the definition, e.g.  sdfProperty/RGBColour/sdfProperty/BlueChannel can be used as a JSON pointer to map to another schema used to describe the on-air data, using a pointer map or @type annotation as in W3C TDs

**Comment by mjkoster** [comment]
IOW .../sdfProperty/RGBColour/sdfProperty/BlueChannel points to the OneDM definition, and this name is used as the invariant in the mapping to on-air schemas and database records, etc.

**Comment by mjkoster** [comment]
```
"sdfProperty": {
  "rgbColour": {
    "type": "object",
    "properties": {
      "redChannel": { "type": "number" },
      "greenChannel": { "type": "number" },
      "blueChannel": { "type": "number" }
    }
  }
}
```

**Comment by mjkoster** [comment]
```
"sdfProperty": {
  "rgbColour": {
    "type": "object",
    "properties": {
      "redChannel": { "sdfRef": "#/sdfData/redChannelType" },
      "greenChannel": { "type": "#/sdfData/greenChannelType" },
      "blueChannel": { "type": "#/sdfData/blueChannelType" }
    }
  }
}
"sdfData": {
  "redChannelType": { "type": "number" },
  "greenChannelType": { "type": "number" },
  "blueChannelType": { "type": "number" }
)

**Comment by cabo** [comment]
s/type/sdfRef/ twice

**Comment by cabo** [comment]
But do you need separate types for the three channels?

**Comment by mjkoster** [comment]
This issue has been resolved by allowing composite sdfData and sdfProperty type to be modeled using json-schema object as in the above RGB component color example.
