### ISSUE TITLE
Feature: "anyOf" construct to model design pattern for overloaded property

### ISSUE THREAD

**Issue by mjkoster** [ietf-wg-asdf/SDF#5]
Some IoT data models combine multiple functions in one property. For example, the start up brightness setting for a Zigbee light bulb reserves some values for behavioral settings "restore last brightness" and " set to minimum".

Here is a proposed design pattern that requires the use of "anyOf"

```
"sdfProperty": {
  "StartUpCurrentLevel": {
    "label": "StartUpCurrentLevel",
    "anyOf": [
      {
        "type": "number",
        "minimum": 1,
        "maximum": 254
      },
      {
        "sdfEnum": {
          "MinimumDeviceValuePermitted": {
            "const": 0
          },
          "SetToPreviousValue": {
            "const": 255
          }
        }
      }
    ]
  }
}
```

**Comment by cabo** [comment]
anyOf and sdfEnum overlap in functionality -- both are choices, but sdfEnum is more powerful as the specific alternative in a choice can be named.  Do we need both mechanisms?

**Comment by mjkoster** [comment]
sdfEnum is meant to be handled as a data type with named selections, where anyOf is meant to provide general purpose optionality without the requirement to name the selections. I believe the requirement to name the selections and casting the construct as a data type are uncomfortable constraints in using sdfEnum as the outer construct in the above example.

**Comment by cabo** [comment]
What if we have two numeric ranges?  We'd want to name them.

**Comment by mjkoster** [comment]
@cabo Interesting... like this?
```
sdfProperty {
  brightnessWithColorTone {
    type number
    sdfEnum {
      warm {
        minimum 0
        maximum 86
      }
      neutral {
        minimum 87
        maximum 166
      }
      cool {
        minimum 167
        maximum 255
      }
    }
  }
}
```

**Comment by cabo** [comment]
See #2 for my current proposal

**Comment by mjkoster** [comment]
Looking at all of the examples, it looks like labeling the choices provides a consistent pattern with sensible pointer constructions. I think we can use some variant of this multiple choice pattern both for enums and for multiple constraints

**Comment by mjkoster** [comment]
We could consider "sdfAny" as a construct that provides for a named set of optional definitions, which solves the naming problem with "choice", provides the equivalent functionality of "anyOf" at a higher level, and provides an alternate construct for mapping enums where a semantic definition is needed.
