### ISSUE TITLE
Limit the `observable` quality to `propertyqualities`?

### ISSUE THREAD

**Issue by JKRhb** [ietf-wg-asdf/SDF#52]
At the moment, all `dataqualities` can be `observable` which allows you to define an SDF model like the following:

```json
{
  "sdfObject": {
    "ExampleObject": {
      "sdfAction": {
        "exampleAction": {
          "sdfInputData": {
            "observable": true
          }
        }
      }
    }
  }
}
```

As observable inputs (and similar examples) probably do not make that much sense, I wanted to discuss defining the `observable` quality only for `propertyqualities` and not for `dataqualities` in general. (This is already the case for Properties in WoT TD, see https://www.w3.org/TR/wot-thing-description11/#propertyaffordance).

**Comment by cabo** [comment]
How is observable here different from readable and writable?

**Comment by JKRhb** [comment]
> How is observable here different from readable and writable?

That is actually a very good question. I suppose the same would apply to these qualities as well. I guess there are options for being consistent here: Either also removing `readable` or `writable` from the generic `dataqualities`, or keeping all three. For the sake of ecosystem/JSO compatibility the latter option should probably be preferred even though it does not make that sense semantically? Or could/should these cases be covered by a mapping file, for example?
