### ISSUE TITLE
Allow affordances at the `sdfThing` level?

### ISSUE THREAD

**Issue by JKRhb** [ietf-wg-asdf/SDF#56]
I am currently dealing with the question of how to map more complex models between SDF and WoT TD. WoT TD does not allow for composition within Thing Descriptions/Thing Models and favors linking instead, which is why you cannot map an SDF model like the following to a single TD/TM:

```json
{
  "sdfThing": {
    "topLevelThing": {
      "label": "Example Thing",
      "sdfObject": {
        "SdfObject1": {
          "label": "Example Object 1",
          "sdfProperty": {
            "exampleStatus": {
              "type": "string"
            }
          }
        },
        "SdfObject2": {
          "label": "Example Object 2"
        },
      }
    }
  }
}
```

Using the linking approach instead (c. f. https://w3c.github.io/wot-thing-description/#thing-model-composition), I arrived at the conclusion that you could convert the SDF model above to multiple TMs like so:

```json
{
  "@context": ["https://www.w3.org/2022/wot/td/v1.1"], 
  "@type" : "tm:ThingModel",
  "title": "Example Thing",
  "links": [
    {
      "rel": "tm:submodel",
      "href": "./SdfObject1.tm.jsonld",
      "type": "application/tm+json",
      "instanceName": "SdfObject1"
    },
    {
      "rel": "tm:submodel",
      "href": "./SdfObject2.tm.jsonld",
      "type": "application/tm+json",
      "instanceName": "SdfObject2"
    }
  ]
}
```

The "submodels" could then simply look like this:

```json
{
  "@context": ["https://www.w3.org/2022/wot/td/v1.1"], 
  "@type" : "tm:ThingModel",
  "title": "Example Object 1",
  "properties": {
    "exampleStatus": {
      "type": "string"
    }
  }
}
```

As you can see, both `sdfObject`s and `sdfThing`s are mapped to TMs. In my opinion, this approach works fine when it comes to mapping from SDF to WoT TD. I noticed, however, that it would not work in the other direction if a TM with `links` pointing to submodels featured interaction affordances itself, as those could not be mapped to the `sdfThing` level. To illustrate this problem, an example TM could look like the following:

```json
{
  "@context": ["https://www.w3.org/2022/wot/td/v1.1"], 
  "@type" : "tm:ThingModel",
  "title": "Example Thing",
  "properties": {
    "exampleProperty": {
      "description": "Not mappable to an sdfThing",
      "type": "string"
    }
  },
  "links": [
    {
      "rel": "tm:submodel",
      "href": "./SdfObject1.tm.jsonld",
      "type": "application/tm+json",
      "instanceName": "SdfObject1"
    },
    {
      "rel": "tm:submodel",
      "href": "./SdfObject2.tm.jsonld",
      "type": "application/tm+json",
      "instanceName": "SdfObject2"
    }
  ]
}
```

I therefore wanted to discuss with you whether it would make sense to add the capability of defining interaction affordances to `sdfThing`s or if these additional affordances should rather be mapped to an additional `sdfObject`.

I think having the possibility to define affordances at the `sdfThing` level would reflect that Things might be more than the sum of their individual parts, so to speak. The combination of a refrigerator and a freezer, for example, might have additional affordances that could be used to monitor or control the Thing as a whole while still being able to control the temperature of the two components individually.

I am looking forward to hearing your thoughts on this issue!

**Comment by cabo** [comment]
I'm leaning towards requiring these affordances to be bundled in an sdfObject.
One question this immediately raises is how to call such an object, often this physical is an additional panel, but that is of course not universal.

**Comment by JKRhb** [comment]
> One question this immediately raises is how to call such an object

That is a very good question – my temporary solution was to use a modified version the sdfThing's key and refer to it in a field called `describedBy` with JSON pointer like so:

```json
{
  "sdfThing": {
    "topLevelThing": {
      "label": "Example Thing",
      "describedBy": "#/sdfThing/topLevelThing/sdfObject/topLevelThingObject"
      "sdfObject": {
        "topLevelThingObject": {
          "sdfProperty":
            "globalStatus": {
              "label": "Status of the sdfThing as a whole",
              ...
            }
        },
        ...
      }
    }
  }
}
```

This is obviously not the best solution yet, but maybe it can serve as a starting point for further discussion.

**Comment by cabo** [comment]
I think we are leaning to wontfix, let's confirm this in an hour.

I'll add a new issue on suggesting a conventional name.

**Comment by akeranen** [comment]
Given this request has come up more than once, and there's no strong reasoning (so far?) for not doing it, I think we could keep this option open for (eco)systems that want to model affordances like this but provide some guidance text in the spec for consideration on the pros and cons.

**Comment by cabo** [comment]
What is "this option" in the above?

**Comment by akeranen** [comment]
> What is "this option" in the above?

Allowing affordances at the `sdfThing` level

**Comment by cabo** [comment]
Might want to lose sdfObject; allow affordances in sdfThing; enable sdfObject as a ".feature 1.1" name for sdfThing

**Comment by mcr** [comment]
NW: _We could take away things, keep the objects, and then make the objects nestable_
