### ISSUE TITLE
Clarify if exponent notation is allowed for min/max limits

### ISSUE THREAD

**Issue by akeranen** [ietf-wg-asdf/SDF#57]
Sometimes it's useful to use exponent notation (e.g., `2e32`) for the limits of numeric values, especially for the maximum value. SDF spec says those are JSON number type so that implies that exponent notation is OK. Perhaps all we need is one example showing how to use that?

**Comment by cabo** [comment]
But maybe we should have an example for an oscilloscope probe with 1e-12 pF ≤ capacitance ≤ 100e-12pF or so.

**Comment by akeranen** [comment]
Good point :-) `2^32` would have been a better example here, so that would be `2**32`. But that's no longer just a number to parse.
