### ISSUE TITLE
Examples for SDFpointers to input/output parameters

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#60]
Continue from #45

**Comment by nwidell** [comment]
ToDo: 
Michael will write up some basic examples

**Comment by cabo** [comment]
Examples might be good, but can also distract.
Can we close this as WONTFIX?

**Comment by mjkoster** [comment]
I don't see anything special about sdfRef etc. pointing to event or action parameters, that would require a special example. Unless there is some unique pattern we want to show, I would agree with Carsten, we don't need another example for this.
