### ISSUE TITLE
Further define syntax of given names (`named<...>`) and quality names

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#67]

**Comment by cabo** [comment]
We may want to further restrict given names (e.g., alnum + "." + "-") and quality names (e.g., alnum + "-")

**Comment by cabo** [comment]
Give guidance to model writers to make it easy to translate SDF names into programming language identifiers as well.

**Comment by cabo** [comment]
Quality names are (lower) camelCase right now.

**Comment by cabo** [comment]
The first item was addressed by #74. Still need to do the other two items:

> * exclude colon (normative) (maybe some more unicode characters, control characters)
> * recommend alphanumeric and dash
> * add recommendation for conversion into programming language

**Comment by cabo** [comment]
Want to allow dot in certain cases

**Comment by cabo** [comment]
Explain how the given name can stand in as the "label"
Explain how the label can be used for emojis etc

**Comment by cabo** [comment]
developers should not have to do translation
use mapping files for adding translations?

**Comment by cabo** [comment]
```
"label": { "en-US" : "foo", "de-DE" : "quax" }

vs.

"label:en-US" : "foo", 
"label:de-DE" : "quax" }
“`

**Comment by nwidell** [comment]
1. exclude colon (normative) (maybe some more unicode characters, control characters)
2. recommend alphanumeric and dash (Carsten will check his notes, note difference wrt quality and given names)
4. add recommendation for conversion into programming language
5. if label is lacking then use given name as label 
6. if you want funky (non-alphanumeric) characters in given name put them in label instead (internationalization issues)
7. do we have the right extension point for internationalization (WoT: string in English, or map w LANG:label, same quality for both)
