### ISSUE TITLE
Issue: does sdfRef add or also override?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-asdf/SDF#7]
https://www.ietf.org/archive/id/draft-ietf-asdf-sdf-00.html#name-use-of-the-sdfref-keyword-t

asks:

ISSUE: Do we want to enable qualities from the source definition to be overridden in future versions?
The above only says "added".
(Yes, we do want to enable overriding, but need to warn specifiers not
to use this in a way that contradicts the referenced semantics.)

**Comment by mjkoster** [comment]
I agree we should allow qualities of a declaration that are copied in using sdfRef to be redefined in the declaration where sdfRef is used. Perhaps a linter would have an optional check and output a warning, but we should allow it in the processing model.

**Comment by cabo** [comment]
OK, that should be easy to do.  A gap here may be that we cannot remove qualities from a referenced definition.  We could do this by setting the quality to null.  For consistency, null would then become a general "no-op" in the resulting set of qualities.
