### ISSUE TITLE
SDF features in SDF files

### ISSUE THREAD

**Issue by akeranen** [ietf-wg-asdf/SDF#75]
Supporting SDF spec evolution with indicating what (future) features the SDF model file uses.

For example

``` json
"info" : {
  "title": "Example of info block with features",
  "feature(s)" : ["relationships"]
}
```

**Comment by cabo** [comment]
Allow namespace references in feature names (= CURIEs)

**Comment by cabo** [comment]
vs. registry for colon-free feature names

**Comment by cabo** [comment]
Special treatment for feature names that start with a number ("versions")

**Comment by cabo** [comment]
(No features are defined for 1.2.)

**Comment by cabo** [comment]
"features" (plural)

**Comment by akeranen** [comment]
Would be used for something critical. Could be "v2" feature or something more specific. For now, just explain that if find something that don't recognise, it's error.
