### ISSUE TITLE
Protocol Bindings vs. Mapping Files

### ISSUE THREAD

**Issue by JKRhb** [ietf-wg-asdf/SDF#76]
The current SDF draft only mentions protocol bindings, but not mapping files:

https://github.com/ietf-wg-asdf/SDF/blob/a7c04d1eb082fefb954c8ce46b7b7ef8f1b250e0/sdf.md?plain=1#L226-L230

Should mapping files be mentioned here additionally, or even replace the protocol binding entry (as they can be seen as a generalization of the concept)?

**Comment by cabo** [comment]
Could also mention mappings draft

**Comment by cabo** [comment]
Ari: "There will  be mechanisms for augmenting these definitions"
This specification does not define these mechanism
~~... one of which has been called "mapping files".~~
reference the mapping draft.

**Comment by cabo** [comment]
Maybe introduce augmentation mechanisms, group "Protocol Bindings" under them, and point to mapping draft for one more such mechanism.
