### ISSUE TITLE
Disallow using both `sdfChoice` and `enum` at the same time?

### ISSUE THREAD

**Issue by JKRhb** [ietf-wg-asdf/SDF#87]
Revisiting the conversion from SDF to WoT, I was wondering how to deal with the edge case where both an `sdfChoice` and an `enum` are defined that contradict each other. For example, at the moment the following SDF model passes validation:

```json
{
  "sdfData": {
    "test": {
      "sdfChoice": {
        "foo": {
          "const": 1
        },
        "bar": {
          "const": 2
        }
      },
      "enum": [
        "foo",
        "bar"
      ]
    }
  }
}
```

Should it be valid to define a model like that? Or would it make sense to either define `enum` and `sdfChoice` as mutually exclusive in the schemas, or to add an assertion that prohibits using both in a set of data qualities?

(A model like this is probably a rare occurrence, however, I was wondering if a converter should raise an exception when encountering it or if, for example, `sdfChoice` should simply be preferred over `enum`.)

**Comment by akeranen** [comment]
I'd go for only allowing one or the other. And when sdfRef'ing enum into definition with sdfChoice or vice versa, merge into sdfChoice.

**Comment by cabo** [comment]
Merging is difficult because suddenly the resolution process would need to do semantics.
We often have that problem when we have multiple attributes that contribute to some semantics...

**Comment by cabo** [comment]
So I think we'll have to allow both and describe the merging process in the presence of both.

**Comment by akeranen** [comment]
So, two steps: merge-patch as before, and as next step "if there is enum left, add all enum entries to sdfChoice". However, removing elements from that enum would then get tricky.
