### ISSUE TITLE
Info block should allow comments

### ISSUE THREAD

**Issue by akeranen** [ietf-wg-asdf/SDF#95]
Currently `$comment` is not allowed in the info block. That would be useful for example conversion tool comments. Suggest to allow that.

**Comment by akeranen** [comment]
Seems like this would be best solved together when explaining the SDF structure of alternating levels (SDF defined labels vs. spec-writer-defined labels).

**Comment by akeranen** [comment]
Probably all blocks (e.g., name space, and future blocks) should allow `$comment`. I'd suggest moving $comment from the "common qualities" section to a section of it's own saying this, and update CDDL accordingly.

**Comment by cabo** [comment]
But not in named<X>!
